name: Build and Validate Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./lib/jquery

    - name: Validate manifest
      run: |
        if ! jq -e . manifest.json > /dev/null 2>&1; then
          echo "Invalid manifest.json" && exit 1
        fi

    - name: Lint JavaScript files
      run: |
        npx eslint src/**/*.js

    - name: Build extension
      run: |
        mkdir -p dist
        cp -r icons lib src manifest.json dist/